version: '3.4'

services:
  customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"

  orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"


  products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"


  search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Products=http://products
      - Services__Customers=http://customers
      - Services__Orders=http://orders
    ports:
      - "6004:80"

